apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-monitoring

resources:
- ../../base/grafana/instance
- ../../base/grafana/dashboards
# - ../../base/grafana/dashboards-openshift

patches:
- target:
    kind: GrafanaDataSource
    name: thanos
  # oc sa get-token grafana-thanos
  patch: |-
    - op: replace
      path: /spec/datasources/0/secureJsonData/httpHeaderValue1
      value: Bearer eyJhbGciO...
- target:
    kind: Grafana
    name: grafana
  patch: |-
    - op: add
      path: /spec/containers/0/args/-
      value: '-openshift-sar={"resource": "namespaces", "verb": "get"}'

